/**
 *@Generated by sagacity-quickvo 4.18
 */
package ${quickVO.voPackage};

import ${quickVO.voPackage}.${quickVO.abstractPath}.Abstract${quickVO.voName};
<#if (quickVO.swaggerModel=="v2")>
import io.swagger.annotations.ApiModel;
</#if>
<#if (quickVO.swaggerModel=="v3")>
import io.swagger.v3.oas.annotations.media.Schema;
</#if>
<#if (quickVO.lombok)>
import lombok.Data;
<#if (quickVO.lombokChain)>
import lombok.experimental.Accessors;
</#if>
</#if>

/**
 * @project <#if (quickVO.projectName?exists)>${quickVO.projectName}</#if>
 * @version <#if (quickVO.version?exists)>${quickVO.version}</#if>
 * <#if (quickVO.tableRemark?exists && quickVO.tableRemark!='')>@description ${quickVO.tableName},${quickVO.tableRemark}</#if>  
 */
<#if (quickVO.swaggerModel=="v2")>
@ApiModel(value="${quickVO.voName}"<#if (quickVO.tableRemark?exists && quickVO.tableRemark!='')>,description="${quickVO.tableRemark}"</#if>)
</#if>
<#if (quickVO.swaggerModel=="v3")>
@Schema(name="${quickVO.voName}"<#if (quickVO.tableRemark?exists && quickVO.tableRemark!='')>,description="${quickVO.tableRemark}"</#if>)
</#if>
<#if (quickVO.lombok)>
@Data
<#if (quickVO.lombokChain)>
@Accessors(chain = true)
</#if>
</#if>
public class ${quickVO.voName} extends Abstract${quickVO.voName} {
	
	/**
	 * 
	 */
	private static final long serialVersionUID = ${quickVO.voSerialUID}L;
}